### ISSUE TITLE
La commande make database-diff semble ne pas fonctionner

### ISSUE THREAD

**Issue by ip512** [fairnesscoop/pictyschool#102]
lorsque je lance `make database-diff` j'ai l'erreur suivante :
```
> api@1.0.0 migration:diff /var/www
> ts-node ./node_modules/.bin/typeorm migration:generate -d migrations -n

Error during migration generation:
TypeError: str.replace is not a function
    at Object.camelCase (/var/www/src/util/StringUtils.ts:9:16)
    at Function.MigrationGenerateCommand.getTemplate (/var/www/src/commands/MigrationGenerateCommand.ts:142:34)
    at Object.<anonymous> (/var/www/src/commands/MigrationGenerateCommand.ts:101:66)
    at step (/var/www/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/var/www/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/var/www/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
```

Je dois ajouter dans le fichier package.json un nom de la migration, et ça fonctionne :
    "migration:diff": "ts-node ./node_modules/.bin/typeorm migration:generate -d migrations -n **MyEntity**",

**Comment by mmarchois** [comment]
Oui il faut rajouter un nom de migration après la commande make. Il faut certainement l'améliorer pour ne pas lancer la commande s'il manque un argument.

**Comment by mmarchois** [comment]
il faut lancer make database-diff MIGRATION_NAME=MyMigration

**Comment by ip512** [comment]
ok merci, j'ai fait une PR pour ajouter cette info dans le commentaire de la commande : https://github.com/fairnesscoop/pictyschool/pull/103
